name: Static checks

on:
- push
- pull_request

jobs:
  static-checks:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/python:3.11-bookworm
      # cgroupns needed to address the following error:
      # write /sys/fs/cgroup/cgroup.subtree_control: operation not supported
      options: --privileged --cgroupns=host
    steps:
    - uses: actions/checkout@v3
    - name: Analysing the code with ruff
      run: |
        pip install -r test-requirements.txt
        ruff format --check
