name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/python:3.11-bookworm
      # cgroupns needed to address the following error:
      # write /sys/fs/cgroup/cgroup.subtree_control: operation not supported
      options: --privileged --cgroupns=host
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        set -e
        apt update && apt install -y podman
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
    - name: Test with unittest
      run: |
        coverage run --source podman_compose -m unittest pytests/*.py
        python -m unittest tests/*.py
        coverage combine
        coverage report
      env:
        TESTS_DEBUG: 1
